export const largeScreen = '106.25em'
export const bigScreen = '81.25em'
export const mediumScreen = '75em'
export const smallScreen = '62.5em'
export const extraSmallScreen = '50em'
export const mobileScreen = '37.5em'
